// How Margo says her lines (read by voice.mjs).
//
// Who she is: twenty years on the Dream Factory's night shift. She has seen
// flying bathtubs and angry pressure cookers, so nothing scares her any
// more, but she still enjoys the show: on the radio she sounds like someone
// leaning back over her third coffee, grinning at her screens.
// - Base tone: lively, amused, wry. She's having fun, and a little tired.
// - Warnings: alert and encouraging, never panicked. A coach calling it
//   from the sideline ("Duck! Nuts!"), not a siren.
// - Praise: pleased, with a smile; not over the moon.
// - Care: gentle, almost in passing. That's her warmth.
// - The one exception is when it really matters (the dreams leaking, Old
//   Hum awake): there she goes quiet and serious, never scared.
// Use: amused, wryly, playfully, teasing, curious, pleased, cheerfully,
// warmly, encouraging, alert, deadpan, dryly, sighs, chuckles, gently,
// softly, quietly, tired. Avoid: shouting, alarmed, urgently, overjoyed,
// gasps, nervously, panicked; and too many flat ones (calmly, flatly,
// matter-of-fact) in a row, or she goes dead.
//
// Each entry is the English line with v3 acting tags woven in (the tags
// are not spoken). Case and punctuation may differ from the line on screen
// (an exclamation mark here gives the take some life), the words may not:
// if they no longer match, the line is read plainly until it is updated here.
export const ACTED = {
  // The Factory.
  hub_intro1: "[warmly] Evening, rookie! [cheerfully] I'm Margo, your night-shift dispatcher at the Dream Factory.",
  hub_intro2: "[gently] A dog called Biscuit is having a bad dream. [cheerfully] The job board's by the window.",
  hub_journal: "[helpfully] Missed something? It's all in the journal, by the shelf.",
  hub_picked: "[pleased] Good pick! Take the lift down. [playfully] Cog knows the way.",
  hub_back1: "[pleased] Welcome back, and in one piece! [chuckles] Coffee's on me.",
  hub_back2: "[warmly] Spend your dream dust at the workbench. [yawns] That's all for tonight!",
  hub_nojob: "[amused] Pick a job at the board first, rookie.",
  hub_radio: "[tired] Margo here. [sighs] Third coffee. [wryly] Board, bench or lift?",
  hub_radio_2: "[whispers] This radio's older than me. [chuckles] Don't tell it I said that.",
  hub_radio_3: "[amused] Cog keeps asking if dreams have Wi-Fi.",
  hub_radio_4: "[contentedly] Quiet night so far. [wryly] Don't jinx it.",
  hub_radio_5: "[curious] Did you know dogs dream in smells? [deadpan] Me neither.",
  hub_radio_6: "[dryly] If the board's empty, blame the sandman's union.",
  hub_radio_7: "[playfully] Testing, testing… yes, you can hear me. [cheerfully] Back to work!",
  hub_radio_8: "[wryly] Rule one of the night shift: [whispers] never trust a happy vacuum cleaner.",
  hub_window_1: "[softly] That's Old Hum out there. [quietly] A hundred years old, and never a night off.",
  hub_window_2: "[playfully] Make a wish! [amused] Cog wished for a second propeller.",
  hub_window_3: "[softly] Pretty, isn't it? [wryly] Don't tell the dreams I said so.",
  hub_window_4: "[quietly] Hear that hum? [softly] Old Hum, snoring. [sighs] Or trying to.",
  hub_bench: "[proudly] The workbench. [playfully] Bring me dust and I'll make your tools purr.",
  hub_greet_1: "[teasing] Back again? The coffee's still hot. [chuckles] Mostly.",
  hub_greet_2: "[cheerfully] Oh, it's you! [amused] Cog's been polishing the lift all night.",
  hub_greet_3: "[wryly] Night shift, rookie. Dreams don't fix themselves.",
  hub_greet_4: "[warmly] Welcome back! [chuckles] Mind the pipes, I've tripped twice already.",
  hub_greet_5: "[pleased] There you are! [teasing] I was about to send Cog looking for you.",
  hub_greet_6: "[cheerfully] Hello again! The board's waiting, [sighs] and so is my fourth coffee.",
  hub_newjob: "[cheerfully] New job on the board: a kid called Ethan. [gently] Big test tomorrow.",
  hub_newjob2: "[cheerfully] New job on the board: Rosie, a cook. [warmly] Her diner opens tomorrow.",
  hub_newjob3: "[gently] New job on the board: Grandpa Joe, retired station master. [softly] He moves out tomorrow.",
  hub_newjob4: "[cheerfully] New job on the board: Sophie, an astronaut. [warmly] Her first spacewalk is tomorrow.",

  // Biscuit's park.
  park_in1: "[curious] You're in. [sniffs] Smells like cut grass and… [amused] tennis balls.",
  park_in2: "[thoughtfully] There should be a few broken anchors around here. [cheerfully] Let's find them!",
  park_foe: "[amused] Squirrels! [wryly] All day Biscuit chases them. [playfully] Tonight they chase us!",
  park_bunny: "[amused] Dust bunnies. One zap each.",
  park_tub: "[baffled] Is that… a bathtub?",
  park_nut: "[alert] Duck! [amused] Nuts!",
  park_buzzer: "[alert] A Buzzer! Watch its orbs.",
  park_knot: "[wryly] A Knot. [amused] It keeps spinning out squirrels!",
  park_tune: "[encouraging] Stay in the ring while it tunes!",
  park_fix1: "[pleased] One down, the sky's clearing! [cheerfully] I'm sending you the Fuzz Vacuum.",
  park_fix2: "[pleased] Two! One more to go.",
  park_memory: "[curious] Ooh, a memory!",
  park_all: "[pleased] All three hold! [curious] Wait… something big is stirring.",
  park_core: "[encouraging] It's under the middle of the lawn. [warmly] Go on, I've got your back.",
  park_retry: "[gently] It's gone back under. [encouraging] Catch your breath and go again.",
  park_boss: "[deadpan] A VACUUM CLEANER. [sighs] Of course.",
  park_suck: "[alert] Don't let it gulp you!",
  park_clog: "[amused] Clogged! [encouraging] Hit the dust bag!",
  park_phase: "[wryly] Now it's furious. [alert] Jump the cord!",
  park_faint: "[gently] Easy, rookie. I pulled you back.",
  park_win: "[cheerfully] Dream fixed! [warmly] Biscuit's snoring like a little engine.",
  park_heart: "[pleased] A pink heart! [playfully] That'll wake you up a bit.",
  park_low_1: "[concerned] You're fading, rookie! [encouraging] Grab a heart!",
  park_low_2: "[concerned] Wakefulness low! [encouraging] Find a pink heart, quick!",
  park_fall_1: "[deadpan] Gravity: one. Rookie: zero.",
  park_fall_2: "[sighs] Again? [teasing] I'm putting up a sign: mind the edge.",
  park_fall_3: "[teasing] You know the ground ends there, right?",
  park_fall_4: "[amused] That's a lot of falling. [teasing] Training for something?",
  park_swarm_1: "[amused] That's a whole fan club behind you!",
  park_swarm_2: "[playfully] Run now, explain later!",
  park_swarm_3: "[teasing] They really like you. [chuckles] Don't let them hug you.",
  park_idle_1: "[curious] All right down there? It's very quiet on my screens.",
  park_idle_2: "[chatty] Fun fact: Biscuit has buried eleven tennis balls in this park.",
  park_idle_3: "[amused] Cog says hi. [chuckles] Well, Cog says beep.",
  park_idle_4: "[whispers] If you see a slipper, don't ask.",

  // Ethan's school.
  school_in1: "[curious] You're in. [wryly] Smells like floor wax and panic.",
  school_in2: "[cheerfully] Three anchors somewhere in this school. [playfully] Find them before the bell!",
  school_pencil: "[wryly] Pencils. Sharp ones. [amused] And they bounce.",
  school_clock: "[alert] A flying alarm clock! [wryly] Don't let it ring.",
  school_slowed: "[amused] Everything's in slow motion! [encouraging] Stay out of its ring!",
  school_backpack: "[wryly] That backpack weighs more than Ethan. [deadpan] And it's angry.",
  school_sharpener: "[alert] A sharpener! [wryly] It's making more pencils.",
  school_dizzy: "[encouraging] It's dizzy! Now's your chance!",
  school_tune: "[encouraging] Stay in the ring! [wryly] Like a fire drill, but louder.",
  school_fix1: "[pleased] One down! [cheerfully] Sending you the Foam Cannon.",
  school_fix2: "[pleased] Two! One more and the halls stop looping.",
  school_all: "[pleased] All three hold! [curious] Uh-oh… something's under the gym floor.",
  school_core: "[encouraging] Head to the gym. [wryly] Doors close behind you, so be ready.",
  school_retry: "[gently] It's back under the floor. [encouraging] Take a breath, then the gym again.",
  school_boss: "[deadpan] A RED PEN. [wryly] Every kid's nightmare.",
  school_strike: "[alert] It's marking you wrong! Off the line!",
  school_blot: "[amused] Blotted! [encouraging] Hit it while it's down!",
  school_phase: "[wryly] Now it's grading on a curve. [deadpan] A mean one.",
  school_faint: "[gently] Easy. [teasing] No detention down there. [warmly] I pulled you back.",
  school_win: "[cheerfully] Dream fixed! [warmly] Ethan's asleep, smiling at a gold star.",
  school_memory: "[curious] A memory! Ethan's, this time.",
  school_heart: "[playfully] Hearts work in school too. Grab it!",
  school_low_1: "[concerned] You're fading! [encouraging] Find a heart!",
  school_low_2: "[concerned] Low on wakefulness, rookie. [encouraging] Heart. Now.",
  school_fall_1: "[deadpan] That's not the stairs.",
  school_fall_2: "[teasing] Hallway rule one: no running off the edge.",
  school_fall_3: "[sighs] Again? [teasing] I'm writing you a hall pass for the ground.",
  school_swarm_1: "[amused] It's like the lunch rush!",
  school_swarm_2: "[playfully] The whole class is after you!",
  school_swarm_3: "[playfully] Run now, explain later!",
  school_idle_1: "[curious] Didn't we pass that locker already?",
  school_idle_2: "[chatty] Fun fact: Ethan lost four pencils this week. [amused] Found one.",
  school_idle_3: "[amused] Cog wants to know if he can join the chess club.",
  school_idle_4: "[curious] Is it just me, or is that clock going backwards?",

  // Rosie's kitchen.
  kitchen_in1: "[curious] You're in. [wryly] Smells like garlic and nerves.",
  kitchen_in2: "[cheerfully] Three anchors in this kitchen. [playfully] Mind your step, everything's huge!",
  kitchen_meatball: "[amused] Meatballs! Angry ones. [encouraging] Don't let them roll you over.",
  kitchen_split: "[deadpan] It split in two! [sighs] Of course it did.",
  kitchen_pepper: "[alert] A pepper shaker. [playfully] Hold your breath!",
  kitchen_sneeze: "[amused] Bless you! [encouraging] Now get out of that cloud.",
  kitchen_rollingpin: "[alert] A rolling pin, coming your way. Jump!",
  kitchen_grinder: "[alert] A meat grinder! [wryly] It's making more meatballs.",
  kitchen_dizzy: "[encouraging] It's dazed! Hit it now!",
  kitchen_tune: "[encouraging] Stay in the ring. [wryly] Like a pot you can't walk away from.",
  kitchen_fix1: "[pleased] One down! [cheerfully] Sending you the Lullaby Bell.",
  kitchen_fix2: "[pleased] Two! One more and the kitchen shrinks back.",
  kitchen_all: "[pleased] All three hold! [curious] Uh-oh… something's whistling under the floor.",
  kitchen_core: "[encouraging] The middle of the floor. [wryly] It closes behind you, so be ready.",
  kitchen_retry: "[gently] It's back under the floor. [encouraging] Catch your breath, then go again.",
  kitchen_boss: "[deadpan] A PRESSURE COOKER. [alert] Don't let it blow!",
  kitchen_whistle: "[alert] It's in the red! Get away from it!",
  kitchen_lid: "[amused] Lid's off! [encouraging] Hit it inside!",
  kitchen_phase: "[wryly] Now it's really boiling.",
  kitchen_faint: "[gently] Easy, chef. [teasing] I pulled you out of the oven.",
  kitchen_win: "[cheerfully] Dream fixed! [warmly] Rosie's asleep, smiling at a full diner.",
  kitchen_memory: "[curious] A memory! Rosie's, this time.",
  kitchen_heart: "[playfully] A heart! Not on the menu, but grab it.",
  kitchen_low_1: "[concerned] You're fading! [encouraging] Find a heart!",
  kitchen_low_2: "[concerned] Low on wakefulness, chef. [encouraging] Heart. Now.",
  kitchen_fall_1: "[teasing] That's a long way down for a teaspoon.",
  kitchen_fall_2: "[teasing] Kitchen rule one: stay on the counter.",
  kitchen_fall_3: "[sighs] Again? [teasing] I'll put you on dish duty.",
  kitchen_swarm_1: "[amused] It's the dinner rush!",
  kitchen_swarm_2: "[playfully] Order up! And it's all coming for you!",
  kitchen_swarm_3: "[playfully] Too many cooks! Run!",
  kitchen_idle_1: "[curious] I've never seen a fridge this tall. [wryly] Or this hungry.",
  kitchen_idle_2: "[chatty] Fun fact: Rosie's diner opens tomorrow at seven.",
  kitchen_idle_3: "[amused] Cog wants to know if he can lick the spoon.",
  kitchen_idle_4: "[sniffs] Does anyone else smell burnt toast?",

  // Grandpa Joe's garden.
  garden_in1: "[curious] You're in. [sniffs] Smells like roses and… [puzzled] coal smoke?",
  garden_in2: "[cheerfully] Three anchors, and the islands keep drifting apart. [encouraging] Hurry!",
  garden_gnome: "[amused] Gnomes! [wryly] Keep your eyes on them.",
  garden_slinger: "[alert] That one's got a slingshot. [wryly] Don't turn your back on it.",
  garden_ticket: "[alert] Train tickets! [wryly] Punched, and sharp at the edges.",
  garden_can: "[wryly] A watering can. You'll want an umbrella for that one.",
  garden_soaked: "[amused] Soaked! [encouraging] Get out from under it.",
  garden_mower: "[alert] A lawnmower! [wryly] Step aside, and do it late.",
  garden_sunflower: "[deadpan] That sunflower's been watching you.",
  garden_dizzy: "[encouraging] It's dazed! Hit it now!",
  garden_tune: "[encouraging] Stay in the ring. [warmly] Plant your feet, like Joe's roses.",
  garden_fix1: "[pleased] One down! [softly] Look up: Joe's lending you his umbrella.",
  garden_fix2: "[pleased] Two! One more and the garden holds together.",
  garden_all: "[pleased] All three hold! [curious] Hear that ticking? It's coming from the station.",
  garden_core: "[encouraging] Over the viaduct, onto the platform. [playfully] Mind the gap.",
  garden_retry: "[gently] It's gone back under the platform. [encouraging] Catch your breath.",
  garden_boss: "[deadpan] THE BIG ALARM CLOCK. [wryly] Time's up, apparently.",
  garden_timesup: "[alert] The slabs! Get off them!",
  garden_key: "[encouraging] Too high to shoot. Ride the wind up and gust that key!",
  garden_unwound: "[amused] It's run down! [encouraging] Hit its face!",
  garden_phase: "[wryly] Now it's really ringing.",
  garden_faint: "[gently] Easy. I pulled you out before the alarm went off.",
  garden_win: "[cheerfully] Dream fixed! [softly] Joe's asleep, and the garden's in bloom.",
  garden_memory: "[softly] A memory. Joe's, and May's.",
  garden_heart: "[pleased] A heart! Grab it.",
  garden_low_1: "[concerned] You're fading! [encouraging] Find a heart!",
  garden_low_2: "[concerned] Low on wakefulness. [teasing] Heart, now, please.",
  garden_fall_1: "[teasing] The falling's supposed to be HIS dream, not yours.",
  garden_fall_2: "[wryly] Mind the edges. They keep drifting.",
  garden_fall_3: "[deadpan] Umbrella. Open. Before the ground.",
  garden_swarm_1: "[amused] It's the whole garden club!",
  garden_swarm_2: "[playfully] Weeds everywhere! Pull them!",
  garden_swarm_3: "[amused] They're multiplying like zucchini!",
  garden_idle_1: "[softly] Joe planted those roses the year they got married.",
  garden_idle_2: "[amused] Cog says the gnomes keep looking at him.",
  garden_idle_3: "[warmly] The 6:15 to Millbrook never once ran late. [proudly] Joe saw to that.",
  garden_idle_4: "[curious] Is it me, or are the islands further apart than before?",

  // Sophie's station.
  space_in1: "[curious] You're in. [playfully] Careful, everything floats up here.",
  space_in2: "[cheerfully] Three anchors. [playfully] Try a jump. Go on.",
  space_robot: "[amused] Wind-up robots! [wryly] Wait till they run down.",
  space_rocket: "[amused] A plush rocket. [wryly] Don't stand where it's pointing.",
  space_top: "[alert] A spinning top! Jump it when it comes.",
  space_mobile: "[softly] The mobile from over her bed. [amused] It throws planets!",
  space_dizzy: "[encouraging] It's wobbling! Hit it now!",
  space_tune: "[encouraging] Stay in the ring. [wryly] Feet on the floor, if you can.",
  space_fix1: "[pleased] One down! [softly] Look, a yo-yo floating down. Sophie's.",
  space_fix2: "[pleased] Two! One more and the station holds together.",
  space_all: "[pleased] All three hold! [softly] The cupola's glowing. Like a night-light.",
  space_core: "[encouraging] North, into the cupola. [curious] Something big is up there.",
  space_retry: "[gently] It's gone dim again. [encouraging] Catch your breath.",
  space_boss: "[deadpan] THE MOON LAMP. [softly] Her night-light. [wryly] Since when does it bite?",
  space_beam: "[alert] Out of the spotlight!",
  space_tide: "[alert] It's pulling you in! Grab a star!",
  space_chain: "[alert] It's nodding off! [encouraging] Lasso the chain, pull it down!",
  space_tethered: "[pleased] Got it down! [encouraging] Hit it while it's lit!",
  space_phase: "[wryly] Now it's wide awake.",
  space_faint: "[gently] Easy. [teasing] I reeled you out before you floated off.",
  space_win: "[cheerfully] Dream fixed! [softly] Sophie's asleep, and Ohio's right below her.",
  space_memory: "[softly] A memory. From home.",
  space_heart: "[pleased] A heart! Grab it.",
  space_low_1: "[concerned] You're fading! [encouraging] Find a heart!",
  space_low_2: "[concerned] Low on wakefulness. [encouraging] Heart, please.",
  space_fall_1: "[deadpan] Space is big. Don't go in it.",
  space_fall_2: "[wryly] Mind the edges. There's no floor out there.",
  space_fall_3: "[teasing] Lasso first. Jump second.",
  space_swarm_1: "[amused] It's a whole toy box!",
  space_swarm_2: "[playfully] Somebody wound them all up!",
  space_swarm_3: "[deadpan] Houston, we have a crowd.",
  space_idle_1: "[softly] Her dad stuck those glow stars up in the real constellations. [warmly] Took him all weekend.",
  space_idle_2: "[amused] Cog says he's always wanted to float. [deadpan] He's always floating.",
  space_idle_3: "[thoughtfully] Sixteen sunrises a day up here. [softly] No wonder she can't sleep.",
  space_idle_4: "[curious] Is it me, or is Ohio right under us?",

  // The finale: quiet and serious, never scared.
  hub_finale1: "[alert] Rookie! [quietly] The lamps… everything's gone dark.",
  hub_finale2: "[quietly] It's Old Hum. [seriously] A hundred years, and he's wide awake.",
  hub_finale4: "[seriously] All week, the glitches leaked out of him. [softly] Go and fix his dream.",
  hub_finale_board: "[gently] Old Hum can wait a night. [encouraging] Need to get stronger? The lift's on backup.",
  hub_finale_back: "[quietly] Welcome back. He's still wide awake out there.",
  hub_finale_radio: "[gently] Out of the window when you're ready. [wryly] Old jobs if you're not.",
  oldhum_in1: "[quietly] You're in. [softly] Nobody's ever been inside Old Hum. Not even me.",
  oldhum_in2: "[gently] Three anchors, same as always. [quietly] Tonight the dreamer is the Factory.",
  oldhum_gate_west2: "[puzzled] Cog? Since when can you open Old Hum's locks?",
  oldhum_cog2: "[softly] …Of course you were. [warmly] You always did hum in your sleep.",
  oldhum_fuzz: "[surprised] Biscuit's squirrels? In here?",
  oldhum_pencil: "[curious] Ethan's pencils. [softly] He kept a bit of every dream.",
  oldhum_meatball: "[amused] Rosie's meatballs. Still cross.",
  oldhum_gnome: "[alert] Joe's gnomes! Don't look. [sighs] Or do. I always forget.",
  oldhum_robot: "[softly] Sophie's robots. The whole week went through him.",
  oldhum_dizzy: "[encouraging] It's wobbling! Hit it now!",
  oldhum_tune: "[encouraging] Stay in the ring. [softly] He's tossing and turning.",
  oldhum_fix1: "[pleased] One down! [softly] And look: a sack of his own dream sand.",
  oldhum_fix2: "[pleased] Two! [softly] His hum's going lower.",
  oldhum_all: "[pleased] All three hold! [quietly] But his heart's still racing.",
  oldhum_core: "[encouraging] North, behind the last lock. [warmly] Cog knows the way.",
  oldhum_faint: "[gently] I've got you. [softly] He's restless, that's all.",
  oldhum_memory: "[softly] A memory. His own, for once.",
  oldhum_heart: "[pleased] A heart! Grab it.",
  oldhum_low_1: "[concerned] You're fading! [encouraging] Find a heart!",
  oldhum_low_2: "[concerned] Low on wakefulness. [encouraging] Heart, please.",
  oldhum_fall_1: "[wryly] Mind the gaps. There's a lot of machine down there.",
  oldhum_fall_2: "[teasing] That's a long way to the oil pan.",
  oldhum_fall_3: "[teasing] Sand first. Then walk.",
  oldhum_swarm_1: "[amused] It's the whole week at once!",
  oldhum_swarm_2: "[wryly] Every glitch we've met, all in one place.",
  oldhum_swarm_3: "[amused] Squirrels, pencils, meatballs… and you.",
  oldhum_idle_1: "[quietly] A hundred years of other people's dreams. [softly] Not one of his own.",
  oldhum_idle_2: "[sniffs] Smells like warm brass in here. [curious] And cocoa, somehow.",
  oldhum_idle_3: "[whispers] Listen. [softly] Under the hum there's a lullaby. A very old one.",
  oldhum_idle_4: "[quietly] Cog's never this quiet. [warmly] He's home, I think.",
  oldhum_boss: "[quietly] That's his heart. Racing. [softly] A hundred years of it.",
  oldhum_clink: "[alert] Don't shoot him! [encouraging] Sand, rookie. Sand!",
  oldhum_yawn: "[pleased] He's yawning! [encouraging] Now, all the sand you've got!",
  oldhum_phase: "[gently] He's fighting it. [encouraging] Keep going.",
  oldhum_asleep: "[whispers] Shh. He's nodding off…",
  oldhum_win: "[whispers] He's asleep. [softly] Old Hum is asleep.",
  oldhum_retry: "[gently] He's racing again. [encouraging] Catch your breath.",
  hub_end1: "[warmly] Here. Coffee. [chuckles] For real this time.",
  hub_end2: "[quietly] Hear that? [softly] He's snoring. First time in a hundred years.",
};
