// How Margo says her lines (read by voice.mjs).
//
// Who she is: twenty years on the Dream Factory's night shift. She has seen
// flying bathtubs and angry pressure cookers, so nothing scares her any
// more, but she still enjoys the show: on the radio she sounds like someone
// leaning back over her third coffee, grinning at her screens.
// - Base tone: lively, amused, wry. She's having fun, and a little tired.
// - Warnings: alert and encouraging, never panicked. A coach calling it
//   from the sideline ("Duck! Nuts!"), not a siren.
// - Praise: pleased, with a smile; not over the moon.
// - Care: gentle, almost in passing. That's her warmth.
// - The one exception is when it really matters (the dreams leaking, Old
//   Hum awake): there she goes quiet and serious, never scared.
// Use: amused, wryly, playfully, teasing, curious, pleased, cheerfully,
// warmly, encouraging, alert, deadpan, dryly, sighs, chuckles, gently,
// softly, quietly, tired. Avoid: shouting, alarmed, urgently, overjoyed,
// gasps, nervously, panicked; and too many flat ones (calmly, flatly,
// matter-of-fact) in a row, or she goes dead.
//
// Each entry is the English line with v3 acting tags woven in (the tags
// are not spoken). Case and punctuation may differ from the line on screen
// (an exclamation mark here gives the take some life), the words may not:
// if they no longer match, the line is read plainly until it is updated here.
export const ACTED = {
  // The Factory.
  hub_intro1: "[warmly] Evening, rookie! [cheerfully] I'm Margo, your night-shift dispatcher at the Dream Factory.",
  hub_intro2: "[gently] A dog called Biscuit is having a bad dream. [cheerfully] The job board's by the window.",
  hub_journal: "[helpfully] Missed something? It's all in the journal, by the shelf.",
  hub_picked: "[pleased] Good pick! Take the lift down. [playfully] Cog knows the way.",
  hub_back1: "[pleased] Welcome back, and in one piece! [chuckles] Coffee's on me.",
  hub_back2: "[warmly] Spend your dream dust at the workbench. [yawns] That's all for tonight!",
  hub_nojob: "[amused] Pick a job at the board first, rookie.",
  hub_radio: "[tired] Margo here. [sighs] Third coffee. [wryly] Board, bench or lift?",
  hub_radio_2: "[whispers] This radio's older than me. [chuckles] Don't tell it I said that.",
  hub_radio_3: "[amused] Cog keeps asking if dreams have Wi-Fi.",
  hub_radio_4: "[contentedly] Quiet night so far. [wryly] Don't jinx it.",
  hub_radio_5: "[curious] Did you know dogs dream in smells? [deadpan] Me neither.",
  hub_radio_6: "[dryly] If the board's empty, blame the sandman's union.",
  hub_radio_7: "[playfully] Testing, testing… yes, you can hear me. [cheerfully] Back to work!",
  hub_radio_8: "[wryly] Rule one of the night shift: [whispers] never trust a happy vacuum cleaner.",
  hub_radio_9: "[tired] Coffee number four. [whispers] Don't tell my doctor.",
  hub_radio_10: "[amused] If you hear static, that's Cog. [chuckles] He hums on the same frequency.",
  hub_radio_11: "[sighs] Six screens, one radio, [wryly] and no idea where my pen is.",
  hub_radio_12: "[amused] Somebody out there is dreaming about cheese. [deadpan] It's on screen three.",
  hub_radio_13: "[wryly] Night shift tip: never count the dreams. [playfully] You'll nod off.",
  hub_radio_14: "[matter-of-fact] I keep a spare sock in the drawer. [deadpan] Long story. Vacuum-related.",
  hub_radio_15: "[tired] Margo here. Still here. [chuckles] Always here.",
  hub_radio_16: "[softly] Old Hum's lullaby has nine verses. [warmly] I know every one.",
  hub_window_1: "[softly] That's Old Hum out there. [quietly] A hundred years old, and never a night off.",
  hub_window_2: "[playfully] Make a wish! [amused] Cog wished for a second propeller.",
  hub_window_3: "[softly] Pretty, isn't it? [wryly] Don't tell the dreams I said so.",
  hub_window_4: "[quietly] Hear that hum? [softly] Old Hum, snoring. [sighs] Or trying to.",
  hub_window_5: "[playfully] Count the stars if you like. [amused] I got to four thousand once.",
  hub_window_6: "[softly] Every light out there is somebody asleep. [wryly] Mostly.",
  hub_window_7: "[curious] See that pipe? [softly] It runs to every bedroom in town.",
  hub_window_8: "[softly] The moon's on our side tonight. [wryly] Nice of it.",
  hub_window_9: "[softly] When I was a rookie, [warmly] I stood right there too.",
  hub_sleep_1: "[softly] Look at him, sleeping like a baby. [amused] A very big, very brass baby.",
  hub_sleep_2: "[quietly] Hear that? Proper snoring. [warmly] A hundred years in the making.",
  hub_sleep_3: "[softly] Edith would be pleased, I think.",
  hub_sleep_4: "[amused] He twitches now and then. [softly] Dreaming of kites, I bet.",
  hub_late_1: "[contentedly] Quiet night. [softly] Just Old Hum, snoring along to his lullaby.",
  hub_late_2: "[warmly] It's Sunday somewhere. He's earned it.",
  hub_late_3: "[wryly] Dreams still break, rookie. [warmly] Just not all at once any more.",
  hub_late_4: "[amused] Cog fell asleep on the workbench again. [softly] I put a blanket on him.",
  hub_late_5: "[proudly] I've cut down to three coffees a night. [teasing] Don't laugh.",
  hub_back_school: "[pleased] Two nights, two broken dreams. [wryly] Must be a full moon.",
  hub_back_kitchen: "[thoughtfully] Three in a row. [seriously] Dreams don't break like this, rookie.",
  hub_back_garden: "[quietly] Did you feel the pipes rattle? [softly] Old Hum turned over in his sleep.",
  hub_back_space: "[quietly] Five dreams in five nights. [seriously] I think I know where they're leaking from.",
  hub_return_1: "[teasing] Back again? [amused] That dream must have missed you.",
  hub_return_2: "[warmly] Welcome back. [pleased] Another one sleeping soundly.",
  hub_return_3: "[pleased] Back in one piece. [teasing] I'm keeping count, you know.",
  hub_return_4: "[pleased] Nice work down there. [amused] I watched the whole thing on screen four.",
  hub_return_5: "[warmly] There you are. [chuckles] The coffee's gone cold, but you're back.",
  hub_bench: "[proudly] The workbench. [playfully] Bring me dream dust and I'll make your tools stronger.",
  hub_greet_1: "[teasing] Back again? The coffee's still hot. [chuckles] Mostly.",
  hub_greet_2: "[cheerfully] Oh, it's you! [amused] Cog's been polishing the lift all night.",
  hub_greet_3: "[wryly] Night shift, rookie. Dreams don't fix themselves.",
  hub_greet_4: "[warmly] Welcome back! [chuckles] Mind the pipes, I've tripped twice already.",
  hub_greet_5: "[pleased] There you are! [teasing] I was about to send Cog looking for you.",
  hub_greet_6: "[cheerfully] Hello again! The board's waiting, [sighs] and so is my fourth coffee.",
  hub_newjob: "[cheerfully] New job on the board: a kid called Ethan. [gently] Big test tomorrow.",
  hub_newjob2: "[cheerfully] The board's lit up again: Rosie, a cook. [warmly] Her diner opens tomorrow.",
  hub_newjob3: "[gently] Another one on the board. Grandpa Joe, retired station master. [softly] He moves out tomorrow.",
  hub_newjob4: "[cheerfully] Board's calling. Sophie, an astronaut. [warmly] Her first spacewalk is tomorrow.",

  // Biscuit's park.
  park_in1: "[curious] You're in. [sniffs] Smells like cut grass and… [amused] tennis balls.",
  park_in2: "[thoughtfully] There should be a few broken anchors around here. [cheerfully] Let's find them!",
  park_foe: "[amused] Squirrels! [wryly] All day Biscuit chases them. [playfully] Tonight they chase us!",
  park_bunny: "[amused] Dust bunnies. One zap each.",
  park_tub: "[baffled] Is that… a bathtub?",
  park_nut: "[alert] Duck! [amused] Nuts!",
  park_buzzer: "[alert] A Buzzer! Watch its orbs.",
  park_knot: "[wryly] A Knot. [amused] It keeps spinning out squirrels!",
  park_tune: "[encouraging] Stay in the ring while it tunes!",
  park_fix1: "[pleased] One down, the sky's clearing! [cheerfully] I'm sending you the Fuzz Vacuum.",
  park_fix2: "[pleased] Two! One more to go.",
  park_memory: "[curious] Ooh, a memory!",
  park_all: "[pleased] All three hold! [curious] Wait… something big is stirring.",
  park_core: "[encouraging] It's under the middle of the lawn. [warmly] Go on, I've got your back.",
  park_retry: "[gently] It's gone back under. [encouraging] Catch your breath and go again.",
  park_boss: "[deadpan] A VACUUM CLEANER. [sighs] Of course.",
  park_suck: "[alert] Don't let it gulp you!",
  park_clog: "[amused] Clogged! [encouraging] Hit the dust bag!",
  park_phase: "[wryly] Now it's furious. [alert] Jump the cord!",
  park_faint: "[gently] Easy, rookie. I pulled you back.",
  park_win: "[cheerfully] Dream fixed! [warmly] Biscuit's snoring like a little engine.",
  park_heart: "[pleased] A pink heart! [playfully] That'll wake you up a bit.",
  park_low_1: "[concerned] You're fading, rookie! [encouraging] Grab a heart!",
  park_low_2: "[concerned] Wakefulness low! [encouraging] Find a pink heart, quick!",
  park_fall_1: "[deadpan] Gravity: one. Rookie: zero.",
  park_fall_2: "[sighs] Again? [teasing] I'm putting up a sign: mind the edge.",
  park_fall_3: "[teasing] You know the ground ends there, right?",
  park_fall_4: "[amused] That's a lot of falling. [teasing] Training for something?",
  park_swarm_1: "[amused] That's a whole fan club behind you!",
  park_swarm_2: "[playfully] Run now, explain later!",
  park_swarm_3: "[teasing] They really like you. [chuckles] Don't let them hug you.",
  park_idle_1: "[curious] All right down there? It's very quiet on my screens.",
  park_idle_2: "[chatty] Fun fact: Biscuit has buried eleven tennis balls in this park.",
  park_idle_3: "[amused] Cog says hi. [chuckles] Well, Cog says beep.",
  park_idle_4: "[whispers] If you see a slipper, don't ask.",
  park_idle_5: "[softly] Dora left her sweater on the couch so Biscuit could sleep on it.",
  park_idle_6: "[amused] I had a dog once. He dreamed of postmen. [chuckles] Never caught one.",
  park_streak_1: "[impressed] Look at you go!",
  park_streak_2: "[amused] Biscuit would be proud. [chuckles] Well, jealous.",
  park_streak_3: "[wryly] That's a lot of fluff. [playfully] I'll send a broom.",
  park_streak_4: "[impressed] Five in a row! [teasing] Who trained you? [chuckles] Oh right, me.",
  park_fight_1: "[encouraging] Keep moving! [wryly] They can't hit what they can't catch.",
  park_fight_2: "[alert] Watch your back. [amused] No, really, behind you!",
  park_fight_3: "[pleased] Nice. [wryly] Very tidy.",
  park_fight_4: "[amused] Twenty years, and squirrels still surprise me.",
  park_fight_5: "[encouraging] Breathe. Aim. [playfully] Zap!",
  park_fight_6: "[warmly] You're doing fine. [wryly] I'd tell you if you weren't.",
  park_fight_7: "[alert] Don't let them corner you!",
  park_fight_8: "[softly] Somewhere, Biscuit's tail is wagging in his sleep.",
  park_bossfight_1: "[encouraging] Keep circling! [amused] It hates that.",
  park_bossfight_2: "[wryly] That thing ate three socks last week. [teasing] Don't be the fourth!",
  park_bossfight_3: "[alert] Mind the nozzle!",
  park_bossfight_4: "[curious] It's slowing down. [wryly] I think.",
  park_bossfight_5: "[dryly] Who leaves a vacuum running all night, anyway?",
  park_bossfight_6: "[gently] Biscuit's hiding under the bed in there somewhere. [encouraging] Finish it!",

  // Ethan's school.
  school_in1: "[sniffs] Floor wax and panic. [wryly] Yep, that's a school.",
  school_in2: "[cheerfully] The anchors are somewhere in these halls. [playfully] Find them before the bell!",
  school_pencil: "[wryly] Pencils. Sharp ones. [amused] And they bounce.",
  school_clock: "[alert] A flying alarm clock! [wryly] Don't let it ring.",
  school_slowed: "[amused] Everything's in slow motion! [encouraging] Stay out of its ring!",
  school_backpack: "[wryly] That backpack weighs more than Ethan. [deadpan] And it's angry.",
  school_sharpener: "[alert] A sharpener! [wryly] It's making more pencils.",
  school_dizzy: "[encouraging] It's dizzy! Now's your chance!",
  school_tune: "[encouraging] Fire drill rules: [playfully] stay inside the lines!",
  school_fix1: "[pleased] That's one! [playfully] Catch: the Foam Cannon's on its way down.",
  school_fix2: "[pleased] Two down! [amused] The halls are almost done looping.",
  school_all: "[pleased] That's the lot! [curious] Hang on… something's moving under the gym floor.",
  school_core: "[encouraging] Head to the gym. [wryly] Doors close behind you, so be ready.",
  school_retry: "[gently] It's back under the floor. [encouraging] Take a breath, then the gym again.",
  school_boss: "[deadpan] A RED PEN. [wryly] Every kid's nightmare.",
  school_strike: "[alert] It's marking you wrong! Off the line!",
  school_blot: "[amused] Blotted! [encouraging] Hit it while it's down!",
  school_phase: "[wryly] Now it's grading on a curve. [deadpan] A mean one.",
  school_faint: "[gently] Out you come. [warmly] No detention, I promise.",
  school_win: "[cheerfully] Out like a light! [warmly] Ethan's smiling at a gold star.",
  school_memory: "[curious] Something of Ethan's. [warmly] Pocket it.",
  school_heart: "[playfully] Hearts work in school too. Grab it!",
  school_low_1: "[concerned] You're nodding off in class! [encouraging] Find a heart.",
  school_low_2: "[concerned] Low on wakefulness, rookie. [encouraging] Heart. Now.",
  school_fall_1: "[deadpan] That's not the stairs.",
  school_fall_2: "[teasing] Hallway rule one: no running off the edge.",
  school_fall_3: "[teasing] I'm writing you a hall pass for the ground.",
  school_swarm_1: "[amused] It's like the lunch rush!",
  school_swarm_2: "[playfully] The whole class is after you!",
  school_swarm_3: "[playfully] They all get detention. [alert] After you run!",
  school_idle_1: "[curious] Didn't we pass that locker already?",
  school_idle_2: "[chatty] Fun fact: Ethan lost four pencils this week. [amused] Found one.",
  school_idle_3: "[amused] Cog wants to know if he can join the chess club.",
  school_idle_4: "[curious] Is it just me, or is that clock going backwards?",
  school_idle_5: "[warmly] Ethan's dad leaves a note in his lunchbox every day. [softly] Every single day.",
  school_idle_6: "[wryly] Somewhere in here is a gym sock older than both of us.",
  school_streak_1: "[pleased] Gold star for you!",
  school_streak_2: "[impressed] Top of the class!",
  school_streak_3: "[amused] Class dismissed. [wryly] For them, anyway.",
  school_streak_4: "[warmly] Ms. Rivera would put that on the wall.",
  school_fight_1: "[encouraging] Keep moving, like the bell's about to ring!",
  school_fight_2: "[teasing] Don't let them put you in the corner!",
  school_fight_3: "[pleased] Correct. [teasing] Now show your work.",
  school_fight_4: "[amused] I still hate pop quizzes. [wryly] Some things never change.",
  school_fight_5: "[alert] Behind you! [playfully] Hall monitor's orders.",
  school_fight_6: "[warmly] Better than I ever did in math, [chuckles] I'll tell you that.",
  school_fight_7: "[teasing] Eyes on your own paper. [alert] And on that pencil!",
  school_fight_8: "[softly] Ethan's holding his lucky pencil in his sleep.",
  school_bossfight_1: "[alert] Stay off the ink!",
  school_bossfight_2: "[wryly] I've had a grudge against red pens since third grade.",
  school_bossfight_3: "[encouraging] Make it chase you! [amused] Pens hate a moving page.",
  school_bossfight_4: "[curious] Its ink's getting thin. [encouraging] Keep at it!",
  school_bossfight_5: "[dryly] Every red mark is just a lesson. [teasing] Tell it that.",
  school_bossfight_6: "[warmly] Ethan studied all week. [encouraging] He's got this, and so have you!",

  // Rosie's kitchen.
  kitchen_in1: "[sniffs] Garlic, butter and nerves. [amused] Rosie's kitchen, all right.",
  kitchen_in2: "[amused] Everything's huge in here! [encouraging] Mind your step, and find those anchors.",
  kitchen_meatball: "[amused] Meatballs! Angry ones. [encouraging] Don't let them roll you over.",
  kitchen_split: "[deadpan] It split in two! [sighs] Of course it did.",
  kitchen_pepper: "[alert] A pepper shaker. [playfully] Hold your breath!",
  kitchen_sneeze: "[amused] Bless you! [encouraging] Now get out of that cloud.",
  kitchen_rollingpin: "[alert] A rolling pin, coming your way. Jump!",
  kitchen_grinder: "[alert] A meat grinder! [wryly] It's making more meatballs.",
  kitchen_dizzy: "[amused] It's seeing stars. [encouraging] Now!",
  kitchen_tune: "[encouraging] Don't walk away from it. [wryly] Like a pot on the boil.",
  kitchen_fix1: "[pleased] First anchor's holding! [cheerfully] Here, take the Lullaby Bell.",
  kitchen_fix2: "[pleased] Another one holding! [amused] The fridge is shrinking already.",
  kitchen_all: "[pleased] Last one holding! [puzzled] Then why is the floor whistling?",
  kitchen_core: "[encouraging] The middle of the floor. [wryly] It closes behind you, so be ready.",
  kitchen_retry: "[gently] Back under the floor, simmering. [encouraging] Take a sip of something and go again.",
  kitchen_boss: "[deadpan] A PRESSURE COOKER. [alert] Don't let it blow!",
  kitchen_whistle: "[alert] It's in the red! Get away from it!",
  kitchen_lid: "[amused] Lid's off! [encouraging] Hit it inside!",
  kitchen_phase: "[wryly] Full boil. [alert] Stand back!",
  kitchen_faint: "[gently] Got you out of the oven. [teasing] Cool down a sec.",
  kitchen_win: "[pleased] That's a wrap! [warmly] Rosie's asleep, dreaming of a full diner.",
  kitchen_memory: "[curious] Something of Rosie's. [warmly] Keep it safe.",
  kitchen_heart: "[playfully] A heart! Not on the menu, but grab it.",
  kitchen_low_1: "[concerned] You're running on fumes. [encouraging] A heart, quick!",
  kitchen_low_2: "[concerned] Wakefulness low, chef. [playfully] Hearts are on the house!",
  kitchen_fall_1: "[teasing] That's a long way down for a teaspoon.",
  kitchen_fall_2: "[teasing] Counters are for standing on. [wryly] Floors can wait.",
  kitchen_fall_3: "[sighs] Keep that up [teasing] and I'll put you on dish duty.",
  kitchen_swarm_1: "[amused] It's the dinner rush!",
  kitchen_swarm_2: "[playfully] Order up! And it's all coming for you!",
  kitchen_swarm_3: "[playfully] Too many cooks! Run!",
  kitchen_idle_1: "[curious] I've never seen a fridge this tall. [wryly] Or this hungry.",
  kitchen_idle_2: "[chatty] Rosie's diner opens at seven sharp. [amused] She's laid the tables twice already.",
  kitchen_idle_3: "[amused] Cog's been eyeing that spoon for a while now.",
  kitchen_idle_4: "[sniffs] Does anyone else smell burnt toast?",
  kitchen_idle_5: "[warmly] Rosie washed dishes in a diner at sixteen. [proudly] Now she's opening her own.",
  kitchen_idle_6: "[playfully] If you find a cookie, it's evidence. [deadpan] Bring it to me.",
  kitchen_streak_1: "[impressed] Rosie would hire you on the spot!",
  kitchen_streak_2: "[pleased] That's how you clear a table!",
  kitchen_streak_3: "[amused] Nearly out of meatballs. [wryly] Nearly.",
  kitchen_streak_4: "[impressed] Faster than the lunch rush, that was!",
  kitchen_fight_1: "[encouraging] Keep stirring! [chuckles] I mean moving.",
  kitchen_fight_2: "[alert] Behind you! [wryly] That's kitchen talk for: behind you.",
  kitchen_fight_3: "[pleased] Clean plate. [playfully] Next!",
  kitchen_fight_4: "[amused] I can't cook, you know. [wryly] Toast, on a good day.",
  kitchen_fight_5: "[gently] Don't rush it. [warmly] Nothing good is rushed.",
  kitchen_fight_6: "[warmly] That's going better [chuckles] than my omelettes ever did.",
  kitchen_fight_7: "[teasing] Keep out of the corners. [amused] That's where the crumbs live.",
  kitchen_fight_8: "[softly] Rosie's stirring in her sleep. [amused] Literally.",
  kitchen_bossfight_1: "[alert] Watch the steam!",
  kitchen_bossfight_2: "[wryly] My mom had one of those. [chuckles] We ate a lot of soup off the ceiling.",
  kitchen_bossfight_3: "[encouraging] Keep it simmering, not boiling!",
  kitchen_bossfight_4: "[curious] The gauge is dropping. [encouraging] Keep it that way!",
  kitchen_bossfight_5: "[dryly] Every cook's nightmare. [deadpan] And every cook's Tuesday.",
  kitchen_bossfight_6: "[warmly] Rosie's diner opens at seven. [encouraging] Let's not be late!",

  // Grandpa Joe's garden.
  garden_in1: "[sniffs] Roses. And… [puzzled] coal smoke? [warmly] Joe's been dreaming of trains again.",
  garden_in2: "[alert] The islands keep drifting apart. [encouraging] Let's get those anchors before they do!",
  garden_gnome: "[amused] Gnomes! [wryly] Keep your eyes on them.",
  garden_slinger: "[alert] That one's got a slingshot. [wryly] Don't turn your back on it.",
  garden_ticket: "[alert] Train tickets! [wryly] Punched, and sharp at the edges.",
  garden_can: "[wryly] A watering can. You'll want an umbrella for that one.",
  garden_soaked: "[amused] Soaked! [encouraging] Get out from under it.",
  garden_mower: "[alert] A lawnmower! [wryly] Step aside, and do it late.",
  garden_sunflower: "[deadpan] That sunflower's been watching you.",
  garden_dizzy: "[alert] Dazed! [encouraging] Go, go!",
  garden_tune: "[warmly] Plant your feet, like Joe's roses, [encouraging] till it holds.",
  garden_fix1: "[softly] Look up. [warmly] Joe's lending you his umbrella.",
  garden_fix2: "[pleased] The islands are drifting back. [encouraging] One to go!",
  garden_all: "[pleased] Done! [curious] Hear that ticking? It's coming from the station.",
  garden_core: "[encouraging] Over the viaduct, onto the platform. [playfully] Mind the gap.",
  garden_retry: "[gently] It's ticking away under the platform again. [encouraging] Your move, when you're ready.",
  garden_boss: "[deadpan] THE BIG ALARM CLOCK. [wryly] Time's up, apparently.",
  garden_timesup: "[alert] The slabs! Get off them!",
  garden_key: "[encouraging] Too high to shoot. Ride the wind up and gust that key!",
  garden_unwound: "[amused] It's run down! [encouraging] Hit its face!",
  garden_phase: "[wryly] It's ringing double time now.",
  garden_faint: "[gently] Pulled you out before the alarm went off. [sighs] Close one.",
  garden_win: "[pleased] There. [softly] Joe's asleep, and the whole garden's in bloom.",
  garden_memory: "[softly] A memory. Joe's, and May's.",
  garden_heart: "[pleased] There's a heart. [playfully] Pick it like a rose.",
  garden_low_1: "[concerned] You're wilting! [encouraging] Find a heart.",
  garden_low_2: "[concerned] Low on wakefulness. [teasing] Heart, now, please.",
  garden_fall_1: "[teasing] The falling's supposed to be HIS dream, not yours.",
  garden_fall_2: "[wryly] Mind the edges. They keep drifting.",
  garden_fall_3: "[deadpan] Umbrella. Open. Before the ground.",
  garden_swarm_1: "[amused] It's the whole garden club!",
  garden_swarm_2: "[playfully] Weeds everywhere! Pull them!",
  garden_swarm_3: "[amused] They're multiplying like zucchini!",
  garden_idle_1: "[softly] Joe planted those roses the year they got married.",
  garden_idle_2: "[amused] The gnomes keep looking at Cog. [chuckles] He's pretending not to notice.",
  garden_idle_3: "[warmly] The 6:15 to Millbrook never once ran late. [proudly] Joe saw to that.",
  garden_idle_4: "[thoughtfully] The islands are further apart than before. [wryly] I'm sure of it.",
  garden_idle_5: "[softly] Fifty years of Sundays in this garden. [warmly] Joe never missed one.",
  garden_idle_6: "[sniffs] Smell that? Cut grass and engine oil. [warmly] Very Joe.",
  garden_streak_1: "[pleased] Weeded! [warmly] Joe would approve.",
  garden_streak_2: "[impressed] Right on schedule! [warmly] Joe would tip his cap.",
  garden_streak_3: "[pleased] Now that's a tidy garden.",
  garden_streak_4: "[impressed] The 6:15 couldn't have kept up with that!",
  garden_fight_1: "[wryly] Look at them. Then don't. [amused] Then do.",
  garden_fight_2: "[alert] Behind you! [sighs] A gnome. Naturally.",
  garden_fight_3: "[pleased] Neat as Joe's rows.",
  garden_fight_4: "[wryly] Garden gnomes. [deadpan] Never trusted them. Never will.",
  garden_fight_5: "[alert] Mind your footing. [wryly] These islands don't wait.",
  garden_fight_6: "[warmly] Joe would put the kettle on for you.",
  garden_fight_7: "[encouraging] Don't let them grow round you like weeds!",
  garden_fight_8: "[softly] May used to sing to these roses. [warmly] Joe still hums it.",
  garden_bossfight_1: "[alert] Watch the slabs!",
  garden_bossfight_2: "[wryly] Forty-one years, Joe was never late. [dryly] This thing wants him late.",
  garden_bossfight_3: "[encouraging] Jump the hands! [wryly] They're slower than they look.",
  garden_bossfight_4: "[curious] Its ticking's slowing. [encouraging] Don't let up!",
  garden_bossfight_5: "[dryly] Somebody should have wound it down in 1968.",
  garden_bossfight_6: "[warmly] Joe's got all the time in the world. [encouraging] Give it back to him!",

  // Sophie's station.
  space_in1: "[cheerfully] Welcome aboard! [playfully] Careful, everything floats up here.",
  space_in2: "[playfully] Go on, try a jump. [amused] I'll wait.",
  space_robot: "[amused] Wind-up robots! [wryly] Wait till they run down.",
  space_rocket: "[amused] A plush rocket. [wryly] Don't stand where it's pointing.",
  space_top: "[alert] A spinning top! Jump it when it comes.",
  space_mobile: "[softly] The mobile from over her bed. [amused] It throws planets!",
  space_dizzy: "[amused] It's wobbling. [encouraging] Give it a nudge!",
  space_tune: "[encouraging] Hold your ground. [amused] Well, your floor.",
  space_fix1: "[pleased] That one's holding! [softly] Look, a yo-yo floating down. Sophie's.",
  space_fix2: "[pleased] Two holding! [cheerfully] The station's steadier already.",
  space_all: "[pleased] The station's holding! [softly] And the cupola's glowing, like a night-light.",
  space_core: "[encouraging] North, into the cupola. [curious] Something big is up there.",
  space_retry: "[gently] It's dimmed again. [encouraging] Take a moment, then back to the cupola.",
  space_boss: "[deadpan] THE MOON LAMP. [softly] Her night-light. [wryly] Since when does it bite?",
  space_beam: "[alert] Out of the spotlight!",
  space_tide: "[alert] It's pulling you in! Grab a star!",
  space_chain: "[alert] It's nodding off! [encouraging] Lasso the chain, pull it down!",
  space_tethered: "[pleased] Got it down! [encouraging] Hit it while it's lit!",
  space_phase: "[wryly] Uh-oh. [deadpan] Full moon.",
  space_faint: "[gently] Reeled you in before you floated off. [softly] Deep breath.",
  space_win: "[cheerfully] Sleeping like a baby! [softly] And Ohio's right below her.",
  space_memory: "[softly] A memory. From home.",
  space_heart: "[pleased] A heart, floating by. [playfully] Catch it!",
  space_low_1: "[concerned] Your signal's fading! [encouraging] Find a heart.",
  space_low_2: "[concerned] Running low up here. [encouraging] Heart, please.",
  space_fall_1: "[deadpan] Space is big. Don't go in it.",
  space_fall_2: "[wryly] There's no floor out there. [deadpan] I checked.",
  space_fall_3: "[teasing] Lasso first. Jump second.",
  space_swarm_1: "[amused] Toy box, meet rookie. [playfully] Rookie, run!",
  space_swarm_2: "[playfully] Somebody wound them all up!",
  space_swarm_3: "[deadpan] Houston, we have a crowd.",
  space_idle_1: "[softly] Her dad stuck those glow stars up in the real constellations. [warmly] Took him all weekend.",
  space_idle_2: "[amused] Cog's always wanted to float. [deadpan] He's always floating.",
  space_idle_3: "[thoughtfully] Sixteen sunrises a day up here. [softly] No wonder she can't sleep.",
  space_idle_4: "[playfully] Ohio's right under us. Wave!",
  space_idle_5: "[softly] From up here, Sophie's whole town fits behind her thumb.",
  space_idle_6: "[amused] Cog just tried to orbit me. [chuckles] He made it twice.",
  space_streak_1: "[impressed] Houston's impressed. [warmly] So am I.",
  space_streak_2: "[playfully] One small step for a rookie. [amused] One big tidy-up.",
  space_streak_3: "[pleased] Toy box tidied!",
  space_streak_4: "[warmly] Sophie's dad would put that in the logbook.",
  space_fight_1: "[amused] Floating counts as moving. [encouraging] Keep it up!",
  space_fight_2: "[alert] Behind you! [wryly] And above. It's space.",
  space_fight_3: "[pleased] Smooth. [playfully] Very zero-g.",
  space_fight_4: "[amused] First time in orbit, [chuckles] and I'm doing it from a chair.",
  space_fight_5: "[encouraging] Land first, then fight!",
  space_fight_6: "[pleased] Ground control is pleased. [deadpan] Ground control is me.",
  space_fight_7: "[encouraging] Don't let them box you in. [wryly] Space is big, use it.",
  space_fight_8: "[softly] Sophie's mom still leaves the porch light on.",
  space_bossfight_1: "[alert] Keep to the shadows!",
  space_bossfight_2: "[wryly] A night-light that bites. [amused] That's new, even for me.",
  space_bossfight_3: "[encouraging] Hang on to a star when it pulls!",
  space_bossfight_4: "[curious] It's dimming. [encouraging] Don't give it a moment!",
  space_bossfight_5: "[softly] Sophie slept under that lamp until she was twelve.",
  space_bossfight_6: "[warmly] Ohio's coming round. [encouraging] Let's have her asleep by then!",

  // The finale: quiet and serious, never scared.
  hub_finale1: "[alert] Rookie! [quietly] The lamps… everything's gone dark.",
  hub_finale2: "[quietly] It's Old Hum. [seriously] A hundred years, and he's wide awake.",
  hub_finale4: "[seriously] All week, the glitches leaked out of him. [softly] Go and fix his dream.",
  hub_finale_board: "[gently] Old Hum can wait a night. [encouraging] Need to get stronger? The lift's on backup.",
  hub_finale_back: "[quietly] Welcome back. He's still wide awake out there.",
  hub_finale_radio: "[gently] Out of the window when you're ready. [wryly] Old jobs if you're not.",
  oldhum_in1: "[quietly] Nobody's ever been inside Old Hum. [softly] Not even me.",
  oldhum_in2: "[gently] Same job as always. [quietly] Only tonight, the dreamer is the Factory.",
  oldhum_gate_west2: "[puzzled] Cog? Since when can you open Old Hum's locks?",
  oldhum_cog2: "[softly] …Of course you were. [warmly] You always did hum in your sleep.",
  oldhum_fuzz: "[surprised] Biscuit's squirrels? In here?",
  oldhum_pencil: "[curious] Ethan's pencils. [softly] He kept a bit of every dream.",
  oldhum_meatball: "[amused] Rosie's meatballs. Still cross.",
  oldhum_gnome: "[alert] Joe's gnomes! Don't look. [sighs] Or do. I always forget.",
  oldhum_robot: "[softly] Sophie's robots. The whole week went through him.",
  oldhum_dizzy: "[alert] That one's reeling. [gently] Finish it gently.",
  oldhum_tune: "[softly] He's tossing and turning. [encouraging] Hold on in there.",
  oldhum_fix1: "[pleased] It's holding. [softly] And look: a sack of his own dream sand.",
  oldhum_fix2: "[pleased] Two! [softly] His hum's going lower.",
  oldhum_all: "[pleased] Every anchor's holding. [quietly] His heart is still racing, though.",
  oldhum_core: "[encouraging] North, behind the last lock. [warmly] Cog knows the way.",
  oldhum_faint: "[gently] I've got you. [softly] He's restless, that's all.",
  oldhum_memory: "[softly] A memory. His own, for once.",
  oldhum_heart: "[softly] A heart. [warmly] He's looking after you too.",
  oldhum_low_1: "[concerned] Don't you nod off before he does. [encouraging] Find a heart.",
  oldhum_low_2: "[concerned] You're fading in there. [encouraging] Heart, please.",
  oldhum_fall_1: "[wryly] Mind the gaps. There's a lot of machine down there.",
  oldhum_fall_2: "[teasing] That's a long way to the oil pan.",
  oldhum_fall_3: "[teasing] Sand first. Then walk.",
  oldhum_swarm_1: "[amused] It's the whole week at once!",
  oldhum_swarm_2: "[wryly] Every glitch we've met, all in one place.",
  oldhum_swarm_3: "[amused] Squirrels, pencils, meatballs… and you.",
  oldhum_idle_1: "[quietly] A hundred years of other people's dreams. [softly] Not one of his own.",
  oldhum_idle_2: "[sniffs] Smells like warm brass in here. [curious] And cocoa, somehow.",
  oldhum_idle_3: "[whispers] Listen. [softly] Under the hum there's a lullaby. A very old one.",
  oldhum_idle_4: "[quietly] Cog's never this quiet. [warmly] He's home, I think.",
  oldhum_idle_5: "[quietly] Every dream in town runs through these pipes. [softly] Every single night.",
  oldhum_idle_6: "[softly] I said goodnight to him at the end of every shift. [quietly] I don't think he ever heard.",
  oldhum_streak_1: "[impressed] The whole week, one at a time.",
  oldhum_streak_2: "[softly] He's breathing easier with every one.",
  oldhum_streak_3: "[warmly] Look at you. [softly] A week ago you were a rookie.",
  oldhum_streak_4: "[pleased] Neat. [amused] Cog says that's how he'd do it.",
  oldhum_fight_1: "[encouraging] Keep moving. [alert] Mind the gears!",
  oldhum_fight_2: "[alert] Behind you! [sighs] A squirrel. Still.",
  oldhum_fight_3: "[softly] Gently does it.",
  oldhum_fight_4: "[quietly] Twenty years I've worked next to him. [softly] Never once been inside.",
  oldhum_fight_5: "[gently] Sand where you can. [softly] He's had enough fighting.",
  oldhum_fight_6: "[warmly] He can tell you're being kind. [softly] I think.",
  oldhum_fight_7: "[alert] Stay out of the corners. [wryly] It's all teeth in here. [amused] Gear teeth.",
  oldhum_fight_8: "[quietly] Hear that? [softly] The gears are slowing.",
  oldhum_bossfight_1: "[softly] Slow and steady. Like a lullaby.",
  oldhum_bossfight_2: "[gently] Sand, not sparks.",
  oldhum_bossfight_3: "[softly] His lamps are dimming. [encouraging] Keep going.",
  oldhum_bossfight_4: "[alert] Mind the rings. [encouraging] Then more sand!",
  oldhum_bossfight_5: "[quietly] A hundred years. [softly] He doesn't even remember how to sleep.",
  oldhum_bossfight_6: "[softly] Edith wanted him to rest on Sundays. [warmly] Let's start tonight.",
  oldhum_boss: "[quietly] That's his heart. Racing. [softly] A hundred years of it.",
  oldhum_clink: "[alert] Don't shoot him! [encouraging] Sand, rookie. Sand!",
  oldhum_yawn: "[pleased] He's yawning! [encouraging] Now, all the sand you've got!",
  oldhum_phase: "[gently] He's fighting it. [encouraging] Keep going.",
  oldhum_asleep: "[whispers] Shh. He's nodding off…",
  oldhum_win: "[whispers] He's asleep. [softly] Old Hum is asleep.",
  oldhum_retry: "[gently] His heart's racing again. [softly] Breathe, then go back to him.",
  hub_end1: "[warmly] Here. Coffee. [chuckles] For real this time.",
  hub_end2: "[quietly] Hear that? [softly] He's snoring. First time in a hundred years.",
  hub_end4: "[warmly] Not a rookie any more, [teasing] are you?",
  hub_end5: "[softly] Old Hum's on the board now too. [wryly] For the odd bad night.",
};
