// Screenshots of the menu screens and in-run overlays.
import { launch, URL } from "./browser.mjs";
const out = process.argv[2] || "ui";
const w = Number(process.argv[3] || 1280), h = Number(process.argv[4] || 720);
const b = await launch();
const p = await b.newPage({ viewport: { width: w, height: h } });
const logs = [];
p.on("pageerror", (e) => logs.push("PAGEERROR " + e.message));
p.on("console", (m) => { if (m.type() === "error") logs.push(m.text()); });
await p.goto(URL, { waitUntil: "load" });
if (process.env.LANG_HU) { await p.evaluate(() => { localStorage.setItem("last-lantern.settings.v1", JSON.stringify({ lang: "hu" })); }); await p.reload(); }
await p.waitForTimeout(2000);
const click = async (sel) => { await p.click(sel); await p.waitForTimeout(700); };
await click("[data-action=play]");
await p.screenshot({ path: `${out}-story.png` });
await click("[data-action=storyNext]");
await p.screenshot({ path: `${out}-run.png` });
await click("[data-action=begin]");
await p.screenshot({ path: `${out}-intro.png` });
await click("[data-action=go]");
await p.evaluate(() => { const R = window.__lastLantern.G.run; for (let i = 0; i < 60 * 25; i++) { if (R.phase !== "play") break; R.step({ mx: Math.cos(i / 200), my: Math.sin(i / 260) }); R.sfx.length = 0; R.hero.hp = R.hero.maxHp; } });
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}-levelup.png` });
await p.evaluate(() => { const R = window.__lastLantern.G.run; R.pickups.push({ kind: "chest", x: R.hero.body.position.x, y: R.hero.body.position.y, t: 0 }); if (R.phase === "levelup") { R.levelUpQueue = 1; R.pickCard(0); } });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}-chest.png` });
await p.keyboard.press("Enter");
await p.waitForTimeout(500);
await p.evaluate(() => { const R = window.__lastLantern.G.run; R.phase = "dead"; R.phaseT = 0; });
await p.waitForTimeout(3500);
await p.screenshot({ path: `${out}-result.png` });
await click("#result [data-action=hearth]");
await p.screenshot({ path: `${out}-hearth.png` });
await click("#menu-hearth [data-action=back]");
await click("#result [data-action=toMain]");
await click("#menu-main [data-action=journal]");
await p.screenshot({ path: `${out}-journal.png` });
await click(".tab[data-tab=arsenal]");
await p.screenshot({ path: `${out}-arsenal.png` });
console.log(logs.join("\n"));
await b.close();
