name: Prod CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: List files after checkout
        run: |
          pwd
          ls
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run build
        id: build
        run: npm install
      - run: npm run build
      - name: List files after build
        run: |
          pwd
          ls
      - name: Create a Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: FTP Deploy to newkrok.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          local-dir: "./build/"
          server-dir: ./web/
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER_NAME}}
          password: ${{secrets.FTP_PASSWORD}}
          exclude: .git* - .git*/** - .vscode/** - .github/** - *.gpg - *.keys
          dangerous-clean-slate: true
